spring:
  profiles:
    active: dev
    
#dev环境
spring:
  profiles: dev
  application: 
    name: springcloud-config-dev
    
    
#test环境
spring:
  profiles: test
  application: 
    name: springcloud-config-test